version: 0.0
os: linux
files:
  - source: /
    destination: /srv/conduit
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: scripts/pull.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 120
      runas: root


